name: Lint

on:
  - push

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linter checks
        uses: actions/setup-node@v3
      - run: make install
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit tests
        uses: actions/setup-node@v3
      - run: make install
      - run: make test
